"""Leak / duplicate audit of the scoped pest dataset - run BEFORE any GPU time.

The disease dataset taught this lesson the expensive way: a val split that shares images with
train makes every downstream number a lie. IP102's official split is not assumed clean here; it
is checked. Nothing is moved or deleted by this script - it reports, and quarantining (if needed)
is a separate, deliberate step.

Checks:
  1. exact duplicates by md5, across splits (train<->val, train<->test, val<->test)
  2. exact duplicates within a split
  3. same filename in different splits with different content
  4. near-duplicate heuristic: same (width, height, filesize) but different md5, across splits

Writes ml/pest_scoped_audit.txt (+ ml/_pest_scoped_dupes.csv for the offending groups).
"""

import csv
import hashlib
import sys
import time
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent
DST = ROOT / "data" / "pest" / "ip102_scoped"
SPLITS = ("train", "val", "test")
IMAGE_SUFFIXES = (".jpg", ".jpeg", ".png")
REPORT = ROOT / "pest_scoped_audit.txt"
DUPES_CSV = ROOT / "_pest_scoped_dupes.csv"
EXPECTED_TOTAL = 27551


def dhash_of(path: Path, size: int = 8) -> int:
    """64-bit difference hash: robust to re-encoding/resizing, cheap for a handful of files."""
    with Image.open(path) as image:
        small = image.convert("L").resize((size + 1, size), Image.LANCZOS)
        pixels = list(small.getdata())
    bits = 0
    for row in range(size):
        base = row * (size + 1)
        for col in range(size):
            if pixels[base + col] > pixels[base + col + 1]:
                bits |= 1 << (row * size + col)
    return bits


def hamming(a: int, b: int) -> int:
    return bin(a ^ b).count("1")


def md5_of(path: Path) -> str:
    digest = hashlib.md5()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> int:
    if not DST.is_dir():
        print(f"missing scoped dataset: {DST} (run ml/build_pest_scoped.py first)")
        return 1

    files = []
    for split in SPLITS:
        split_dir = DST / split
        if not split_dir.is_dir():
            print(f"missing split: {split_dir}")
            return 1
        for class_dir in sorted(split_dir.iterdir()):
            if not class_dir.is_dir():
                continue
            for image in sorted(class_dir.iterdir()):
                if image.suffix.lower() in IMAGE_SUFFIXES:
                    files.append((split, class_dir.name, image))

    out = []
    add = out.append
    add("SCOPED PEST DATASET AUDIT - duplicate / leak check")
    add("generated by ml/audit_pest_scoped.py")
    add("")
    add(f"dataset: {DST}")
    add(f"files: {len(files)}  (manifest expected {EXPECTED_TOTAL})")
    per_split = defaultdict(int)
    for split, slug, _ in files:
        per_split[split] += 1
    for split in SPLITS:
        add(f"  {split}: {per_split[split]}")

    started = time.time()
    hashes = {}
    with ThreadPoolExecutor(max_workers=12) as pool:
        futures = {pool.submit(md5_of, path): (split, slug, path) for split, slug, path in files}
        for i, future in enumerate(futures, 1):
            split, slug, path = futures[future]
            hashes[path] = future.result()
            if i % 5000 == 0:
                add(f"  hashed {i}/{len(files)} ({time.time() - started:.0f}s)")
                print(f"  hashed {i}/{len(files)}", flush=True)
    add(f"  hashing done in {time.time() - started:.0f}s (12 threads)")

    by_hash = defaultdict(list)
    for split, slug, path in files:
        by_hash[hashes[path]].append((split, slug, path.name))

    cross_groups = []
    within_groups = []
    for digest, members in by_hash.items():
        splits = {m[0] for m in members}
        if len(members) > 1 and len(splits) > 1:
            cross_groups.append((digest, members))
        elif len(members) > 1:
            within_groups.append((digest, members))

    direction = defaultdict(int)
    for _, members in cross_groups:
        present = sorted({m[0] for m in members})
        for a in range(len(present)):
            for b in range(a + 1, len(present)):
                direction[f"{present[a]}<->{present[b]}"] += 1

    add("")
    add("1. EXACT DUPLICATES ACROSS SPLITS (the leak that matters)")
    add(f"   duplicate groups spanning splits: {len(cross_groups)}")
    add(f"   images involved: {sum(len(m) for _, m in cross_groups)}")
    if direction:
        for pair, count in sorted(direction.items()):
            add(f"   {pair}: {count} groups")
        add("   examples (up to 20):")
        for digest, members in cross_groups[:20]:
            add(f"     {digest[:12]}  " + " | ".join(f"{s}/{slug}/{name}" for s, slug, name in members))
    else:
        add("   none - no md5 shared between train/val/test")

    add("")
    add("2. EXACT DUPLICATES WITHIN A SPLIT")
    add(f"   groups: {len(within_groups)}")
    if within_groups:
        add("   examples (up to 10):")
        for digest, members in within_groups[:10]:
            add(f"     {digest[:12]}  " + " | ".join(f"{s}/{slug}/{name}" for s, slug, name in members))

    name_map = defaultdict(set)
    for split, slug, path in files:
        name_map[path.name].add((split, hashes[path]))
    name_conflicts = {
        name: entries
        for name, entries in name_map.items()
        if len({split for split, _ in entries}) > 1 and len({digest for _, digest in entries}) > 1
    }
    add("")
    add("3. SAME FILENAME IN DIFFERENT SPLITS WITH DIFFERENT CONTENT")
    add(f"   names: {len(name_conflicts)}")
    add("   (IP102 ids are globally unique, so any entry here means the split is not the official one)")

    def header(path: Path):
        with Image.open(path) as image:
            return (image.width, image.height, path.stat().st_size)

    started = time.time()
    with ThreadPoolExecutor(max_workers=12) as pool:
        headers = list(pool.map(header, [p for _, _, p in files]))
    add(f"  image headers read in {time.time() - started:.0f}s")

    started = time.time()
    with ThreadPoolExecutor(max_workers=12) as pool:
        dhashes = list(pool.map(dhash_of, [p for _, _, p in files]))
    add(f"  dHash computed for {len(dhashes)} images in {time.time() - started:.0f}s")

    entries = [
        (split, slug, path.name, sig, digest)
        for (split, slug, path), sig, digest in zip(files, headers, dhashes)
    ]

    # Exhaustive cross-split sweep: only images of the same pixel size can be the same photo,
    # so bucket by (w, h) and compare every cross-split pair inside each bucket.
    buckets = defaultdict(list)
    for entry in entries:
        buckets[(entry[3][0], entry[3][1])].append(entry)
    near_pairs = []
    for members in buckets.values():
        if len(members) < 2:
            continue
        for i in range(len(members)):
            for j in range(i + 1, len(members)):
                a, b = members[i], members[j]
                if a[0] == b[0]:
                    continue
                distance = hamming(a[4], b[4])
                if distance <= 6:
                    near_pairs.append((distance, a, b))
    near_pairs.sort(key=lambda item: item[0])

    by_dhash = defaultdict(list)
    for entry in entries:
        by_dhash[entry[4]].append(entry)
    identical_groups = [m for m in by_dhash.values() if len({e[0] for e in m}) > 1]

    add("")
    add("4. NEAR-DUPLICATE SWEEP (exhaustive cross-split dHash, same pixel size, distance<=6)")
    add(f"   cross-split near-duplicate pairs: {len(near_pairs)}")
    for distance, a, b in near_pairs[:40]:
        add(f"     dHash={distance:<3} {a[0]}/{a[2]} ({a[1]})  <->  {b[0]}/{b[2]} ({b[1]})")
    add("")
    add("5. IDENTICAL dHash ACROSS SPLITS (distance 0, any size)")
    add(f"   groups: {len(identical_groups)}")
    for members in identical_groups[:20]:
        add("     " + " | ".join(f"{s}/{slug}/{name}" for s, slug, name, _, _ in members))
    verdict = (
        "LEAK-FREE"
        if not cross_groups and not name_conflicts and not near_pairs and not identical_groups
        else "REVIEW REQUIRED"
    )
    add("")
    add(f"VERDICT: {verdict}")
    add(f"  exact cross-split duplicates (md5): {len(cross_groups)}")
    add(f"  filename conflicts across splits: {len(name_conflicts)}")
    add(f"  cross-split near-duplicates (dHash<=6, same pixel size): {len(near_pairs)}")
    add(f"  cross-split identical dHash (distance 0, any size): {len(identical_groups)}")
    add(f"  within-split duplicates: {len(within_groups)} (not a leak, but label noise to know about)")
    add("")
    add("ACTION: every pair whose members sit in different splits is a soft leak. Quarantining the")
    add("  TRAINING-side member is enough to make the val/test member honest. This script moves")
    add("  nothing; the quarantining step is separate and deliberate.")

    REPORT.write_text("\n".join(out) + "\n", encoding="utf-8")
    with DUPES_CSV.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["kind", "md5", "split", "slug", "filename"])
        for digest, members in cross_groups:
            for split, slug, name in members:
                writer.writerow(["cross-split", digest, split, slug, name])
        for digest, members in within_groups:
            for split, slug, name in members:
                writer.writerow(["within-split", digest, split, slug, name])
        for distance, a, b in near_pairs:
            for member in (a, b):
                writer.writerow([f"near-dup-dHash{distance}", "", member[0], member[1], member[2]])

    print(f"wrote {REPORT.name}; VERDICT {verdict}", flush=True)
    print(f"  cross-split duplicate groups: {len(cross_groups)}", flush=True)
    print(f"  filename conflicts: {len(name_conflicts)}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
