"""Quantify the quarantine needed for the scoped pest dataset (dry run - moves nothing).

Input: ml/_pest_neardup_pairs.csv from ml/pest_neardup_verify.py (cross-split pairs at MAE<=10).

Reasoning encoded here: a model is trained only on `train`, so only a *train* image can leak into
val or test. A val<->test pair does not make either split dishonest, it just marks the dataset as
burst-photographed. So the minimal honest fix is: remove the train-side member of every pair whose
other member is in val or test. Quarantined files are listed for a separate, deliberate move.

Writes ml/pest_quarantine_plan.txt and ml/_pest_quarantine_list.csv.
"""

import csv
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PAIRS = ROOT / "_pest_neardup_pairs.csv"
PLAN = ROOT / "pest_quarantine_plan.txt"
LIST = ROOT / "_pest_quarantine_list.csv"
DST = ROOT / "data" / "pest" / "ip102_scoped"


def main() -> int:
    if not PAIRS.is_file():
        print(f"missing {PAIRS}")
        return 1

    rows = list(csv.DictReader(PAIRS.open(encoding="utf-8")))
    train_files = {}
    paired_splits = defaultdict(set)
    per_class = defaultdict(int)
    val_test_rows = []

    for row in rows:
        a = (row["split_a"], row["slug_a"], row["file_a"])
        b = (row["split_b"], row["slug_b"], row["file_b"])
        if {a[0], b[0]} == {"train"}:
            continue
        if a[0] == "train":
            train, other = a, b
        elif b[0] == "train":
            train, other = b, a
        else:
            val_test_rows.append((a, b))  # val<->test: does not affect training honesty
            continue
        train_files[(train[1], train[2])] = train[1]
        paired_splits[(train[1], train[2])].add(other[0])
        per_class[train[1]] += 1

    # val<->test pairs matter less, but val chooses the best epoch, so a test image twinned in val
    # still biases the final number. The val-side member is the one to drop; test stays untouched.
    val_side = set()
    for a, b in val_test_rows:
        if a[0] == "val":
            val_side.add((a[1], a[2]))
        if b[0] == "val":
            val_side.add((b[1], b[2]))
    test_val_pairs = len(val_test_rows)

    counts = defaultdict(int)
    for split in ("train", "val", "test"):
        for class_dir in sorted((DST / split).iterdir()):
            if class_dir.is_dir():
                counts[(split, class_dir.name)] = sum(1 for _ in class_dir.iterdir())

    out = []
    add = out.append
    add("PEST DATASET QUARANTINE PLAN (dry run - nothing moved)")
    add("generated by ml/pest_quarantine_plan.py from ml/_pest_neardup_pairs.csv")
    add("")
    add(f"cross-split near-duplicate pairs (MAE<=10): {len(rows)}")
    add(f"  involving a train image (these leak into eval): "
        f"{sum(1 for r in rows if 'train' in (r['split_a'], r['split_b']))}")
    add(f"  val<->test only (harmless for training honesty): {test_val_pairs}")
    add("")
    add(f"TRAIN images to quarantine: {len(train_files)}")
    add("  per-class removals (before -> after):")
    for slug in sorted(per_class):
        before = counts[("train", slug)]
        after = before - len([1 for (s, f), _ in train_files.items() if s == slug])
        add(f"    {slug:<34} {before:>5} -> {after:>5}  (-{before - after})")

    add("")
    add(f"VAL images to quarantine for the val<->test pairs: {len(val_side)}")
    add("  (val picks the best epoch, so a test image twinned in val still biases the final test")
    add("   number; the test split itself is never modified)")
    for slug, name in sorted(val_side)[:25]:
        add(f"    val/{slug}/{name}")
    if len(val_side) > 25:
        add(f"    ... and {len(val_side) - 25} more")

    add("")
    add("val/test images that have a train near-duplicate (become honest once the train side goes):")
    eval_images = defaultdict(set)
    for row in rows:
        a = (row["split_a"], row["file_a"])
        b = (row["split_b"], row["file_b"])
        for member, other in ((a, b), (b, a)):
            if member[0] in ("val", "test") and other[0] == "train":
                eval_images[member[0]].add(member[1])
    for split in ("val", "test"):
        add(f"    {split}: {len(eval_images[split])} images")

    add("")
    add("files to move (train side only) -> ml/data/pest/quarantine/neardup_train/")
    for (slug, name), _ in sorted(train_files.items())[:25]:
        add(f"    train/{slug}/{name}")
    if len(train_files) > 25:
        add(f"    ... and {len(train_files) - 25} more (full list in {LIST.name})")

    PLAN.write_text("\n".join(out) + "\n", encoding="utf-8")
    with LIST.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["split", "slug", "filename", "reason"])
        for (slug, name), _ in sorted(train_files.items()):
            writer.writerow(["train", slug, name, "near-duplicate in val/test (MAE<=10)"])
        for slug, name in sorted(val_side):
            writer.writerow(["val", slug, name, "near-duplicate in test (MAE<=10)"])

    print(f"wrote {PLAN.name}: train={len(train_files)} val={len(val_side)} images to quarantine",
          flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
