"""Verify the near-duplicate candidates with actual pixel comparison.

ml/audit_pest_scoped.py flagged cross-split pairs at dHash<=6 plus groups with an identical dHash.
A 64-bit dHash can collide on IP102's flat white laboratory backgrounds, so "same dHash" is a
candidate, not a verdict. This script re-checks every candidate by comparing 24x24 grayscale pixels
(mean absolute error) and reports the MAE distribution, so the threshold is chosen from evidence
instead of asserted.

Writes ml/pest_neardup_verification.txt and ml/_pest_neardup_pairs.csv (pairs with MAE<=10).
Nothing is moved.
"""

import csv
import sys
import time
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent
DST = ROOT / "data" / "pest" / "ip102_scoped"
SPLITS = ("train", "val", "test")
IMAGE_SUFFIXES = (".jpg", ".jpeg", ".png")
REPORT = ROOT / "pest_neardup_verification.txt"
PAIRS_CSV = ROOT / "_pest_neardup_pairs.csv"
GRID = 24
DHASH_LIMIT = 6


def signature(path: Path):
    """(w, h, dHash64, 24x24 grayscale bytes)"""
    with Image.open(path) as image:
        gray = image.convert("L")
        width, height = gray.size
        pixels = bytes(gray.resize((GRID, GRID), Image.LANCZOS).getdata())
        hash_pixels = list(gray.resize((9, 8), Image.LANCZOS).getdata())
    bits = 0
    for row in range(8):
        base = row * 9
        for col in range(8):
            if hash_pixels[base + col] > hash_pixels[base + col + 1]:
                bits |= 1 << (row * 8 + col)
    return (width, height, bits, pixels)


def hamming(a: int, b: int) -> int:
    return bin(a ^ b).count("1")


def mae(a: bytes, b: bytes) -> float:
    return sum(abs(x - y) for x, y in zip(a, b)) / len(a)


def main() -> int:
    if not DST.is_dir():
        print(f"missing scoped dataset: {DST}")
        return 1

    files = []
    for split in SPLITS:
        split_dir = DST / split
        for class_dir in sorted(split_dir.iterdir()):
            if not class_dir.is_dir():
                continue
            for image in sorted(class_dir.iterdir()):
                if image.suffix.lower() in IMAGE_SUFFIXES:
                    files.append((split, class_dir.name, image))

    started = time.time()
    with ThreadPoolExecutor(max_workers=12) as pool:
        sigs = list(pool.map(signature, [p for _, _, p in files]))
    print(f"signatures: {len(sigs)} in {time.time() - started:.0f}s", flush=True)

    entries = [
        (split, slug, path.name, sig[0], sig[1], sig[2], sig[3])
        for (split, slug, path), sig in zip(files, sigs)
    ]

    buckets = defaultdict(list)
    for entry in entries:
        buckets[(entry[3], entry[4])].append(entry)

    pairs = []
    for members in buckets.values():
        if len(members) < 2:
            continue
        for i in range(len(members)):
            for j in range(i + 1, len(members)):
                a, b = members[i], members[j]
                if a[0] == b[0]:
                    continue
                distance = hamming(a[5], b[5])
                if distance <= DHASH_LIMIT:
                    pairs.append((mae(a[6], b[6]), distance, a, b))
    pairs.sort(key=lambda item: item[0])

    identical = defaultdict(list)
    for entry in entries:
        identical[entry[5]].append(entry)
    identical_groups = [m for m in identical.values() if len({e[0] for e in m}) > 1]

    buckets_hist = [(0, 2), (2, 5), (5, 10), (10, 20), (20, 40), (40, 256)]
    out = []
    add = out.append
    add("NEAR-DUPLICATE VERIFICATION - pixel comparison of every dHash candidate")
    add("generated by ml/pest_neardup_verify.py")
    add("")
    add(f"images: {len(entries)}   cross-split candidates (same size, dHash<={DHASH_LIMIT}): {len(pairs)}")
    add(f"identical-dHash groups spanning splits: {len(identical_groups)}")
    add("")
    add("MAE distribution over the candidate pairs (24x24 grayscale, 0-255):")
    add(f"  {'MAE range':<12} {'pairs':>6}   interpretation")
    interpretations = {
        (0, 2): "re-encoded / near-identical copy - same photo",
        (2, 5): "almost certainly the same photo (burst series or resize)",
        (5, 10): "very close framing - same subject series",
        (10, 20): "same scene, different frame - suspicious",
        (20, 40): "probably different images sharing a plain background",
        (40, 256): "different images (dHash collision)",
    }
    for low, high in buckets_hist:
        count = sum(1 for p in pairs if low <= p[0] < high)
        add(f"  {low}-{high:<8} {count:>6}   {interpretations[(low, high)]}")

    add("")
    add("cross-class pairs (different slug) among the candidates - potential label noise:")
    cross_class = [p for p in pairs if p[2][1] != p[3][1]]
    add(f"  count: {len(cross_class)}")
    for value, distance, a, b in cross_class[:15]:
        add(f"    MAE={value:6.2f} dHash={distance:<3} {a[0]}/{a[1]}/{a[2]}  <->  {b[0]}/{b[1]}/{b[2]}")

    add("")
    add("closest 25 pairs overall:")
    for value, distance, a, b in pairs[:25]:
        add(f"    MAE={value:6.2f} dHash={distance:<3} {a[0]}/{a[1]}/{a[2]}  <->  {b[0]}/{b[1]}/{b[2]}")

    confirmed = [p for p in pairs if p[0] <= 10]
    add("")
    add(f"pairs at or below MAE 10 (quarantine candidates): {len(confirmed)}")
    images_involved = len(
        {(p[2][0], p[2][2]) for p in confirmed} | {(p[3][0], p[3][2]) for p in confirmed}
    )
    add(f"distinct images involved: {images_involved}")
    split_pairs = defaultdict(int)
    for _, _, a, b in confirmed:
        split_pairs["<->".join(sorted({a[0], b[0]}))] += 1
    for key in sorted(split_pairs):
        add(f"  {key}: {split_pairs[key]} pairs")

    REPORT.write_text("\n".join(out) + "\n", encoding="utf-8")
    with PAIRS_CSV.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["mae", "dhamming", "split_a", "slug_a", "file_a", "split_b", "slug_b", "file_b"])
        for value, distance, a, b in confirmed:
            writer.writerow([f"{value:.2f}", distance, a[0], a[1], a[2], b[0], b[1], b[2]])

    print(f"wrote {REPORT.name}: candidates={len(pairs)} confirmed(<=10)={len(confirmed)} "
          f"cross-class={len(cross_class)}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
